; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.20"

; Modules
; contrib
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "1.6"

projects[admin_theme][subdir] = "contrib"
projects[admin_theme][version] = "1.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.8"

projects[cck][subdir] = "contrib"
projects[cck][version] = "2.9"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.23"

projects[dialog][subdir] = "contrib"
projects[dialog][version] = "1.0-alpha2"

projects[evoc][subdir] = "contrib"
projects[evoc][version] = "1.0-alpha2"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "1.0-beta10"

projects[jquery_ui][subdir] = "contrib"
projects[jquery_ui][version] = "1.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.0-alpha1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[node_import][subdir] = "contrib"
projects[node_import][version] = "1.1"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.9"

projects[panels_tabs][subdir] = "contrib"
projects[panels_tabs][version] = "1.0-rc6"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.5"

projects[rdf][subdir] = "contrib"
projects[rdf][version] = "1.0-alpha8"

projects[rdfcck][subdir] = "contrib"
projects[rdfcck][version] = "2.x-dev"

projects[rdfproxy][subdir] = "contrib"
projects[rdfproxy][version] = "1.x-dev"

projects[recaptcha][subdir] = "contrib"
projects[recaptcha][version] = "1.5"

projects[schema][subdir] = "contrib"
projects[schema][version] = "1.7"

projects[semanticviews][subdir] = "contrib"
projects[semanticviews][version] = "1.1"

projects[sparql][subdir] = "contrib"
projects[sparql][version] = "1.0-alpha1"

projects[tabs][subdir] = "contrib"
projects[tabs][version] = "1.3"

projects[token][subdir] = "contrib"
projects[token][version] = "1.15"

projects[views_tabs][subdir] = "contrib"
projects[views_tabs][version] = "1.0-beta1"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "1.0-beta3"


; Patched
projects[views][subdir] = "patched"
projects[views][version] = "3.0-alpha3"
; Patches added to support sparql_views
projects[views][patch][] = "http://drupal.org/files/issues/views_621142-16_2_0_1_0.patch"
projects[views][patch][] = "http://srvgal12.deri.ie/views_621142-39.patch"
; Broken/missing handler
projects[views][patch][] = "http://drupal.org/files/issues/views_broken-handler_953716_3.patch"

projects[sparql_views][subdir] = "patched"
projects[sparql_views][download][type] = "git"
projects[sparql_views][download][url] = "git@github.com:istos/sparql_views.git"
projects[sparql_views][type] = "module"


; Sandbox
projects[rdfimporter][subdir] = "contrib"
projects[rdfimporter][download][type] = "git"
projects[rdfimporter][download][url] = "http://git.drupal.org/sandbox/milesw/1085078.git"
projects[rdfimporter][type] = "module"


; Features
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[indicatornode][download][type] = ""
;projects[indicatornode][download][url] = ""
;projects[indicatornode][type] = "module"
;projects[indicatornode][subdir] = "sites/all/modules/features/indicatornode"
;projects[indicatornode][version] = "1.1-dev"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[indicatorresults][download][type] = ""
;projects[indicatorresults][download][url] = ""
;projects[indicatorresults][type] = "module"
;projects[indicatorresults][subdir] = "sites/all/modules/features/indicatorresults"
;projects[indicatorresults][version] = "1.3-dev"


; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;projects[ldp][download][type] = ""
;projects[ldp][download][url] = ""
;projects[ldp][type] = "theme"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.

projects[rubik][version] = "3.0-beta2"
projects[rubik][type] = "theme"

projects[tao][version] = "3.2"
projects[tao][type] = "theme"

projects[jake][location] = http://code.developmentseed.org/fserver
projects[jake][version] = 1.0-beta15


; Libraries
libraries[arc][download][type] = "git"
libraries[arc][download][url] = "https://github.com/semsol/arc2.git"
libraries[arc][directory_name] = "arc"
libraries[arc][type] = "library"

libraries[flot][download][type] = "file"
libraries[flot][download][url] = "http://flot.googlecode.com/files/flot-0.7.zip"
libraries[flot][directory_name] = "flot"
libraries[flot][type] = "library"

libraries[tinymce][download][type] = "file"
libraries[tinymce][download][url] = "https://github.com/downloads/tinymce/tinymce/tinymce_3.4.1_jquery.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery-ui-1.7.3.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "modules/contrib/jquery_ui"

libraries[jsplumb][download][type] = "get"
libraries[jsplumb][download][url] = "http://jsplumb.googlecode.com/files/jquery.jsPlumb-1.2.3-all-min.js"
libraries[jsplumb][destination] = "modules/patched/sparql_views/js"

